### ISSUE TITLE
The "Add Mentor Review" page needs to match the Resources layout.

### ISSUE THREAD

**Issue by ryan-hamblin** [BloomTech-Labs/underdog-devs-fe-a#282]
As per the Stakeholder's request @nathancai97 went ahead and implemented some work for UnderDog Devs FE. This issue is set up to capture that work that was done via Jira.

@paulstgermain will you please help ensure that @nathancai97 's work is accounted for via Jira?

**Comment by nathancai97** [comment]
I've updated the 'Add Mentor Review' page to mirror the same layout as the 'Resources' page.
<img width="1717" alt="Screen Shot 2022-08-09 at 6 58 35 PM" src="https://user-images.githubusercontent.com/96
<img width="1719" alt="Screen Shot 2022-08-09 at 6 58 14 PM" src="https://user-images.githubusercontent.com/96900578/183779511-518c6987-d2b9-469a-a159-dbe55d747814.png">
900578/183779503-41e008c2-e748-4109-b0f3-020a11375
<img width="1725" alt="Screen Shot 2022-08-09 at 6 58 08 PM" src="https://user-images.githubusercontent.com/96900578/183779519-9c692e44-5298-4a7a-840b-80e12f556a80.png">
4a3.png">

**Comment by nathancai97** [comment]
I've updated the 'Add Mentor Review' page to mirror the same layout as the 'Resources' page.
<img width="1717" alt="Screen Shot 2022-08-09 at 6 58 35 PM" src="https://user-images.githubusercontent.com/96900578/183779565-cc69e938-8f38-4e5e-8cdc-a19589ed9ad0.png">
<img width="1719" alt="Screen Shot 2022-08-09 at 6 58 14 PM" src="https://user-images.githubusercontent.com/96900578/183779571-cbadfe48-e594-4eaa-a144-7b0f5ff828f6.png">
<img width="1725" alt="Screen Shot 2022-08-09 at 6 58 08 PM" src="https://user-images.githubusercontent.com/96900578/183779576-7716565f-07fd-4ecf-a22a-ffc4de09272b.png">

**Comment by nathancai97** [comment]
I've updated the 'Add Mentor Review' page to mirror the same layout as the 'Resources' page.
<img width="1725" alt="Screen Shot 2022-08-09 at 6 58 08 PM" src="https://user-images.githubusercontent.com/96900578/183779620-e19608eb-2150-4c3a-ae57-4295d0061a67.png">
<img width="1717" alt="Screen Shot 2022-08-09 at 6 58 35 PM" src="https://user-images.githubusercontent.com/96900578/183779636-b3d209a0-9184-43f4-9fb8-f3fa122ab56c.png">
<img width="1719" alt="Screen Shot 2022-08-09 at 6 58 14 PM" src="https://user-images.githubusercontent.com/96900578/183779646-361d3273-deea-4406-83d6-2510faf24030.png">

**Comment by nathancai97** [comment]
I've updated the 'Add Mentor Review' page to mirror the same layout as the 'Resources' page.
<img width="1719" alt="Screen Shot 2022-08-09 at 6 58 14 PM" src="https://user-images.githubusercontent.com/96900578/183779690-b24c38f6-113a-492c-ba7c-1185f1801065.png">
<img width="1725" alt="Screen Shot 2022-08-09 at 6 58 08 PM" src="https://user-images.githubusercontent.com/96900578/183779702-0c6e8c1f-ffb1-47d3-b53c-372bf909a2db.png">
<img width="1717" alt="Screen Shot 2022-08-09 at 6 58 35 PM" src="https://user-images.githubusercontent.com/96900578/183779712-c3b00a70-63a9-43cd-937b-0d54ccc15004.png">

**Comment by nathancai97** [comment]
I've also gone and updated the MenteeAddReview.js to reflect the same changes I did to the MentorAddReview.js, although we aren't currently utilizing that component.

**Comment by jpivvt** [comment]
Ticket added to Jira https://bloomtechlabs.atlassian.net/browse/BL-795
