### ISSUE TITLE
Login logic flow

### ISSUE THREAD

**Issue by mcfrr3** [BloomTech-Labs/underdog-devs-fe-a#317]
In reviewing the Auth0 cleanup code it became clear to me that the flow for logging in has been a bit muddled and isn't very clear - more to the point, doesn't make sense where it's happening and doesn't seem like it will work correctly. Currently the login steps happen in the `Navbar` component, which doesn't make a lot of sense to me. In my mind, this should be logic that happens in the very beginning of loading the app, before components have started loading (not during the loading of a sub-component). There's also the fact that there is dummy-data being used in the back-end when loading a user profile that should be updated now that Auth0 in the FE *should* be working. 

My proposal:

- FE: Move the login logic from `Navbar.js` into the `App` component in `index.js`. 
  - Get the necessary info from `useAuth0()` to send the `profileId` to the BE (there's a user object that is made available after the user has authenticated. Make use of `isAuthenticated`, also provided by Auth0).
- BE: Update the logic in the `authRequired.js` middleware to actually use the profile, based on the `profileId` that is passed from the FE
  - This requires receiving the Auth0 `profileId` or email and retrieving the corresponding profile from the postgres DB, where we have the role recorded, which should be passed back to the FE and saved to state (used for many components)

Helpful reference to what can be destructured from `useAuth0()`: https://auth0.github.io/auth0-react/modules.html

**Comment by ryan-hamblin** [comment]
Thanks @mcfrr3 we ended up capturing this work and I forgot to close out the issue.
