### ISSUE TITLE
A possible update is needed in the Environment Variables in notion

### ISSUE THREAD

**Issue by JamesFincher** [BloomTech-Labs/underdog-devs-fe-a#326]
In my pr [here](https://github.com/BloomTech-Labs/underdog-devs-fe-a/pull/325), I had to update the .env file entry for the ds api url from `DS_API_URL `to `REACT_APP_DS_API_URL`. Without this change, any attempt to use process.env would result in undefined. It is my assumption this change will be needed to be implemented project wide, as this is the first implementation I could find attempting to parse the .env on the front end.

**Comment by ryan-hamblin** [comment]
@paulstgermain wanna make sure our `.env vars` are up to date?
