### ISSUE TITLE
BL-997 non-auth landing page breaking feature

### ISSUE THREAD

**Issue by roxannebobby** [BloomTech-Labs/underdog-devs-fe-a#329]
This ticket is approved by @ryan-hamblin. 

As was laid out in the loom video below, there are two separate (but related issues) to bundle together here. 

Research what the root of the issues are by following the steps outlined below:

- Reproduce the bug yourself and document the steps it takes to reproduce the issue.

- Truly understand the root of the problem. Don't assume anything. I have only assumptions about why these things are broken right now. I'd need to dig in further to find out what the cause is.

- Fix the issue the way you know how.

- Test the fix. 

Auth0 breaks the non-auth landing page when user lands on it.
User unable to navigate back to the landing if not logged in.

[Loom video link here](https://www.loom.com/share/e7aff08ab5de4d20a14006986e3aecfa)

Recommended story points: 5

**Comment by ryan-hamblin** [comment]
@roxannebobby and @joanterm I'm closing this issue to move it into our backlog. You should see it in our ready for work lane at some point in the near future.
